AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  openai-app-back
  
  Sample SAM Template for openai-app-back

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128
  # # FIXME:↓ここを追加したらエラー発生
  # Api:
  #   Cors:
  #     AllowOrigin: "'*'"
  #     AllowCredentials: true
  #     AllowMethods: "'POST'"
  #     AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

Resources:
  ChatgptSearchWordFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: chatgpt-search-word/
      Handler: chatgpt-search-word
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies: # 新規追加
        - TranslateFullAccess
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search/word
            Method: GET
            RequestParameters: # 新規追加
              "method.request.path.q":
                Required: true
                Caching: false
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        # 新規追加
        Variables:
          API_KEY: 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
  # FIXME:↓ここを追加したらエラー発生
  # ChatgptSearchWordAPI:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: 'Prod'
  #     Cors:
  #       AllowOrigin: "'*'" # TODO:環境によって許可範囲を設定 (ex.http://127.0.0.1:3000
  #       AllowCredentials: true
  #       AllowMethods: "'POST'"
  #       AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ChatgptSearchWordAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/word/"
  ChatgptSearchWordFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ChatgptSearchWordFunction.Arn
  ChatgptSearchWordFunctionIamRole:
    Description: "Implicit IAM Role created for ChatgptSearchWordFunction"
    Value: !GetAtt ChatgptSearchWordFunctionRole.Arn
