# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

# デプロイ方法 #
# sam deploy --config-env default
# sam deploy --config-env dev
# sam deploy --config-env stage
# sam deploy --config-env prod
#



### default環境 ###
[default]
[default.global.parameters]
stack_name = "lambda-chatgpt"
[default.build.parameters]
cached = true
parallel = true
[default.validate.parameters]
lint = true
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "duran-open-ai"
s3_prefix = "lambda-chatgpt"
region = "ap-northeast-1"
disable_rollback = true
image_repositories = []
[default.package.parameters]
s3_bucket = "duran-open-ai"
[default.sync.parameters]
watch = true
[default.local_start_api.parameters]
warm_containers = "EAGER"
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

### dev環境 ###
[dev]
[dev.global.parameters]
stack_name = "lambda-chatgpt"
[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "duran-open-ai"
s3_prefix = "lambda-chatgpt-dev"
region = "ap-northeast-1"
disable_rollback = true
image_repositories = []
[dev.package.parameters]
s3_bucket = "duran-open-ai"

### stage環境 ###
[stage]
[stage.global.parameters]
stack_name = "lambda-chatgpt"
[stage.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "duran-open-ai"
s3_prefix = "lambda-chatgpt-stage"
region = "ap-northeast-1"
disable_rollback = true
image_repositories = []
[stage.package.parameters]
s3_bucket = "duran-open-ai"

### prod環境 ###
[prod]
[prod.global.parameters]
stack_name = "lambda-chatgpt"
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "duran-open-ai"
s3_prefix = "lambda-chatgpt-prod"
region = "ap-northeast-1"
disable_rollback = true
image_repositories = []
[prod.package.parameters]
s3_bucket = "duran-open-ai"
